version: 2.1

orbs:
  request-aws: benjlevesque/request-aws@0.2.0

workflows:
  version: 2
  cd:
    jobs:
      - deploy

jobs:
  deploy:
    docker: 
      - image: circleci/python
    steps:
      - checkout
      - request-aws/k8s-install
      - request-aws/k8s-configure
      - run: kubectl apply -n default --recursive -f kubernetes
